version: "3.9"  # optional since v1.27.0
services:
  web_api:
    image: web_api
    container_name: web_api_application
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql_server2022;Database=salaries;User Id=SA;Password=123qweASD@@;MultipleActiveResultSets=true;TrustServerCertificate=true
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=123qweASD@@