// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pishtazan.Salaries.Persistence;

#nullable disable

namespace Pishtazan.Salaries.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230826141416_AddUniqIndexToFirstAndLastNameColumns")]
    partial class AddUniqIndexToFirstAndLastNameColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pishtazan.Salaries.Domain.Employees.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Pishtazan.Salaries.Domain.Employees.Employee", b =>
                {
                    b.OwnsOne("Pishtazan.Salaries.Domain.Employees.FullName", "FullName", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .HasColumnType("int");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");

                            b1.OwnsOne("Pishtazan.Salaries.Domain.Employees.FirstName", "FirstName", b2 =>
                                {
                                    b2.Property<int>("FullNameEmployeeId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)")
                                        .HasColumnName("FirstName");

                                    b2.HasKey("FullNameEmployeeId");

                                    b2.ToTable("Employees");

                                    b2.WithOwner()
                                        .HasForeignKey("FullNameEmployeeId");
                                });

                            b1.OwnsOne("Pishtazan.Salaries.Domain.Employees.LastName", "LastName", b2 =>
                                {
                                    b2.Property<int>("FullNameEmployeeId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)")
                                        .HasColumnName("LastName");

                                    b2.HasKey("FullNameEmployeeId");

                                    b2.ToTable("Employees");

                                    b2.WithOwner()
                                        .HasForeignKey("FullNameEmployeeId");
                                });

                            b1.Navigation("FirstName")
                                .IsRequired();

                            b1.Navigation("LastName")
                                .IsRequired();
                        });

                    b.OwnsMany("Pishtazan.Salaries.Domain.Employees.IncomeDetail", "Incomes", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.HasKey("EmployeeId", "Id");

                            b1.ToTable("IncomeDetail");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");

                            b1.OwnsOne("Pishtazan.Salaries.Domain.Common.Salaries.Income", "Income", b2 =>
                                {
                                    b2.Property<int>("IncomeDetailEmployeeId")
                                        .HasColumnType("int");

                                    b2.Property<int>("IncomeDetailId")
                                        .HasColumnType("int");

                                    b2.Property<long>("Value")
                                        .HasColumnType("bigint")
                                        .HasColumnName("Income");

                                    b2.HasKey("IncomeDetailEmployeeId", "IncomeDetailId");

                                    b2.ToTable("IncomeDetail");

                                    b2.WithOwner()
                                        .HasForeignKey("IncomeDetailEmployeeId", "IncomeDetailId");
                                });

                            b1.OwnsOne("Pishtazan.Salaries.Domain.Common.Salaries.SalaryDetail", "SalaryDetails", b2 =>
                                {
                                    b2.Property<int>("IncomeDetailEmployeeId")
                                        .HasColumnType("int");

                                    b2.Property<int>("IncomeDetailId")
                                        .HasColumnType("int");

                                    b2.HasKey("IncomeDetailEmployeeId", "IncomeDetailId");

                                    b2.ToTable("IncomeDetail");

                                    b2.WithOwner()
                                        .HasForeignKey("IncomeDetailEmployeeId", "IncomeDetailId");

                                    b2.OwnsOne("Pishtazan.Salaries.Domain.Common.Salaries.Allowance", "Allowance", b3 =>
                                        {
                                            b3.Property<int>("SalaryDetailIncomeDetailEmployeeId")
                                                .HasColumnType("int");

                                            b3.Property<int>("SalaryDetailIncomeDetailId")
                                                .HasColumnType("int");

                                            b3.Property<long>("Value")
                                                .HasColumnType("bigint")
                                                .HasColumnName("Allowance");

                                            b3.HasKey("SalaryDetailIncomeDetailEmployeeId", "SalaryDetailIncomeDetailId");

                                            b3.ToTable("IncomeDetail");

                                            b3.WithOwner()
                                                .HasForeignKey("SalaryDetailIncomeDetailEmployeeId", "SalaryDetailIncomeDetailId");
                                        });

                                    b2.OwnsOne("Pishtazan.Salaries.Domain.Common.Salaries.BasicSalary", "BasicSalary", b3 =>
                                        {
                                            b3.Property<int>("SalaryDetailIncomeDetailEmployeeId")
                                                .HasColumnType("int");

                                            b3.Property<int>("SalaryDetailIncomeDetailId")
                                                .HasColumnType("int");

                                            b3.Property<long>("Value")
                                                .HasColumnType("bigint")
                                                .HasColumnName("BasicSalary");

                                            b3.HasKey("SalaryDetailIncomeDetailEmployeeId", "SalaryDetailIncomeDetailId");

                                            b3.ToTable("IncomeDetail");

                                            b3.WithOwner()
                                                .HasForeignKey("SalaryDetailIncomeDetailEmployeeId", "SalaryDetailIncomeDetailId");
                                        });

                                    b2.OwnsOne("Pishtazan.Salaries.Domain.Common.Salaries.Transportation", "Transportation", b3 =>
                                        {
                                            b3.Property<int>("SalaryDetailIncomeDetailEmployeeId")
                                                .HasColumnType("int");

                                            b3.Property<int>("SalaryDetailIncomeDetailId")
                                                .HasColumnType("int");

                                            b3.Property<long>("Value")
                                                .HasColumnType("bigint")
                                                .HasColumnName("Transportation");

                                            b3.HasKey("SalaryDetailIncomeDetailEmployeeId", "SalaryDetailIncomeDetailId");

                                            b3.ToTable("IncomeDetail");

                                            b3.WithOwner()
                                                .HasForeignKey("SalaryDetailIncomeDetailEmployeeId", "SalaryDetailIncomeDetailId");
                                        });

                                    b2.Navigation("Allowance")
                                        .IsRequired();

                                    b2.Navigation("BasicSalary")
                                        .IsRequired();

                                    b2.Navigation("Transportation")
                                        .IsRequired();
                                });

                            b1.OwnsOne("Pishtazan.Salaries.Domain.Employees.Date", "Date", b2 =>
                                {
                                    b2.Property<int>("IncomeDetailEmployeeId")
                                        .HasColumnType("int");

                                    b2.Property<int>("IncomeDetailId")
                                        .HasColumnType("int");

                                    b2.Property<DateTime>("GregorianDate")
                                        .HasColumnType("datetime2")
                                        .HasColumnName("Date");

                                    b2.HasKey("IncomeDetailEmployeeId", "IncomeDetailId");

                                    b2.ToTable("IncomeDetail");

                                    b2.WithOwner()
                                        .HasForeignKey("IncomeDetailEmployeeId", "IncomeDetailId");
                                });

                            b1.Navigation("Date")
                                .IsRequired();

                            b1.Navigation("Income")
                                .IsRequired();

                            b1.Navigation("SalaryDetails")
                                .IsRequired();
                        });

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("Incomes");
                });
#pragma warning restore 612, 618
        }
    }
}
